FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY CityComplaintApi/*.csproj ./CityComplaintApi/
RUN dotnet restore CityComplaintApi/CityComplaintApi.csproj

COPY CityComplaintApi/. ./CityComplaintApi/
RUN dotnet publish CityComplaintApi/CityComplaintApi.csproj -c Release -o /app/publish /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app

ENV ASPNETCORE_URLS=http://+:8080
ENV ASPNETCORE_ENVIRONMENT=Production

COPY --from=build /app/publish .
EXPOSE 8080

ENTRYPOINT ["dotnet", "CityComplaintApi.dll"]
